// Generated by CoffeeScript 1.4.0

(function(exports) {
  exports.Deromanize = function(x) {
    var ch, chars, max, numerals, re, total, _i, _len;
    re = /^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/;
    if (!(typeof x === 'string' && re.test(x))) {
      return 0;
    }
    numerals = {
      'M': 1000,
      'D': 500,
      'C': 100,
      'L': 50,
      'X': 10,
      'V': 5,
      'I': 1
    };
    chars = x.split('').reverse();
    max = total = 0;
    for (_i = 0, _len = chars.length; _i < _len; _i++) {
      ch = chars[_i];
      total += numerals[ch] >= max ? numerals[ch] : -numerals[ch];
      max = Math.max(max, numerals[ch]);
    }
    return total;
  };
  return exports.Romanize = function(x) {
    var key, numerals, result;
    if (!(+x && (0 <= x && x <= 3999))) {
      return '';
    }
    numerals = {
      'M': 1000,
      'CM': 900,
      'D': 500,
      'CD': 400,
      'C': 100,
      'XC': 90,
      'L': 50,
      'XL': 40,
      'X': 10,
      'IX': 9,
      'V': 5,
      'IV': 4,
      'I': 1
    };
    result = '';
    while (x >= 1) {
      for (key in numerals) {
        if (numerals[key] > x) {
          continue;
        }
        x -= numerals[key];
        result += key;
        break;
      }
    }
    return result;
  };
})(typeof exports === 'undefined' ? this['romanize'] = {} : exports);
